name: Generate sources

on:
  push:
    branches:
      - feature/wrapper
    paths:
      - 'hello/random/path/**'

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Commit sources
        run: |
          set -ex
          echo "hello" >> hello.txt
          git config --global user.name 'generator'
          git config --global user.email 'generator@users.noreply.github.com'
          git add -A
          git commit -m "Automated generation"
          git push
